#!/bin/bash

cd "$(dirname "${BASH_SOURCE[0]}")" || exit 1

BASE=$(pwd)
ln -sf $BASE/gitconfig ~/.gitconfig
# ln -sf $BASE/zshrc ~/.zshrc
# ln -sf $BASE/tmux.conf ~/.tmux.conf

# tmux source-file ~/.tmux.conf
# $BASE/install-vim

# Install zsh and oh-my-zsh
# dnf install -y zsh
# sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

# git clone https://github.com/geometry-zsh/geometry $HOME/.oh-my-zsh/custom/themes


# Install golang
# GO_VERSION=1.21.12
# GO_FILE=go$GO_VERSION.linux-amd64.tar.gz

# if [ ! -f $GO_FILE ]
#     wget https://go.dev/dl/$GO_FILE
# fi
# sudo rm -rf /usr/local/go && sudo tar -C /usr/local -xzf $GO_FILE
# rm $GO_FILE
