#!/bin/bash

cd $(dirname $BASH_SOURCE)
BASE=$(pwd)

export GIT_SSL_NO_VERIFY=true
mkdir -p ~/.vim/autoload
curl --insecure -fLo ~/.vim/autoload/plug.vim https://raw.github.com/junegunn/vim-plug/master/plug.vim

# vimrc
mv -v ~/.vimrc ~/.vimrc.old 2> /dev/null
ln -sf $BASE/vimrc ~/.vimrc

# nvim
mkdir -p ~/.config/nvim
ln -sf $BASE/init.vim ~/.config/nvim/init.vim
# ln -sf ~/.vim/autoload/plug.vim ~/.config/nvim/autoload/

mkdir -p ~/.config/nvim/lua
ln -sf $BASE/lua/lsp_config.lua ~/.config/nvim/lua/lsp_config.lua

ln -sf $BASE/snippets ~/.config/nvim/snippets

vi +PlugInstall +qall
