#!/bin/bash

cd "$(dirname "${BASH_SOURCE[0]}")" || exit 1

BASE=$(pwd)
ln -sf $BASE/gitconfig ~/.gitconfig
ln -sf $BASE/zshrc ~/.zshrc
ln -sf $BASE/tmux.conf ~/.tmux.conf

tmux source-file ~/.tmux.conf
$BASE/install-vim

